### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mechamaya** [aalitor/WPF_Circular-Progress-Bar#2]
This is one of the best Circular Progress Bars I've found for WPF, and I would like to use it in my project with a custom style. However there is no license listed on your GitHub page. Are people permitted to use or modify this code with credit to the original author?

**Comment by aalitor** [comment]
No problem to use it in your project for me. The projects generally are public and open source in this platform and you can use them unless the authors protects their source code or have a license to prevent copying the project. So use it like your own :)

**Comment by Ippo343** [comment]
Hi @aalitor , I'd like to use your control in an application I'm developing, but I really can't risk it unless you choose an explicit license.
Do you think it would be possible for you to pick one and add it to the repo?
Judging from your statement above, I think that MIT would suit you.

Thanks!

**Comment by vara-mr** [comment]
@aalitor, could you please choose an explicit licensing type for your project? This would help us to use your control with proper approvals.
